<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\MaterialEditor.Base\UI\UI.ShaderUiMetadata.cs"
             Link="UI.ShaderUiMetadata.cs" />
    <Compile Include="..\..\src\MaterialEditor.Base\UI\UI.TooltipPolicy.cs"
             Link="UI.TooltipPolicy.cs" />
    <Compile Include="..\..\src\MaterialEditor.Core\Core.MaterialEditor.SiruSyncPolicy.cs"
             Link="Core.MaterialEditor.SiruSyncPolicy.cs" />
  </ItemGroup>
</Project>
