<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyName>KK_MoreOutfits</AssemblyName>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- NuGet packaging properties -->
    <IsPackable>true</IsPackable>
    <PackageId>MoreOutfits.Koikatu</PackageId>
    <PackageDescription>Allows user to add more outfit slots to characters</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\ListTemplate.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IllusionModdingAPI.KKAPI" Version="1.45.1" />
  </ItemGroup>
  <Import Project="..\MoreOutfits.Core\MoreOutfits.Core.projitems" Label="Shared" />
  <Import Project="..\Shared\Shared.projitems" Label="Shared" />
</Project>